INSERT INTO WINE(wineId, name, origin, imageURL) VALUES('wine1', 'Chateau Pontet Barrail 2012 Medoc', 'France', 'http://wine1.png');
INSERT INTO WINE(wineId, name, origin, imageURL) VALUES('wine2', 'Chateau Fonbadet 2011 Pauillac', 'France', 'http://wine2.png');
INSERT INTO WINE(wineId, name, origin, imageURL) VALUES('wine3', 'Abarbanel Special Reserve Rouge 2016', 'France', 'http://wine4.png');
INSERT INTO WINE(wineId, name, origin, imageURL) VALUES('wine4', 'Winemaker''s Selection Un Double Cabernet Franc 2017', 'France', 'http://wine4.png');
INSERT INTO WINE(wineId, name, origin, imageURL) VALUES('wine5', 'Maison Roche de Bellene, Vieilles Vignes Pinot Noir 2014 Bourgogne', 'France', 'http://wine5.png');
INSERT INTO WINE(wineId, name, origin, imageURL) VALUES('wine6', 'Luce Della Vite Lucente', 'Italy', 'http://wine6.png');
INSERT INTO WINE(wineId, name, origin, imageURL) VALUES('wine7', 'Castello di Monsanto Chianti Classico Riserva 2010', 'Italy', 'http://wine7.png');
INSERT INTO WINE(wineId, name, origin, imageURL) VALUES('wine8', 'Damilano Barolo Cannubi 2010', 'Italy', 'http://wine8.png');
INSERT INTO WINE(wineId, name, origin, imageURL) VALUES('wine9', 'Frescobaldi Castiglioni Chianti', 'Italy', 'http://wine9.png');
INSERT INTO WINE(wineId, name, origin, imageURL) VALUES('wine10', 'Beni di Batasiolo Barbaresco', 'Italy', 'http://wine10.png');
INSERT INTO WINE(wineId, name, origin, imageURL) VALUES('wine11', 'Beringer California Cabernet Sauvignon 2012', 'USA', 'http://wine11.png');